import { jsPDF } from "jspdf";
import { ProductionLine } from "../types";

export function generateDailyYieldPDF(lines: ProductionLine[], date: string) {
  const doc = new jsPDF({
    orientation: "portrait",
    unit: "mm",
    format: "a4",
  });

  const totalLines = lines.length;
  const totalTarget = lines.reduce((acc, l) => acc + l.targetPcs, 0);
  const totalProduction = lines.reduce((acc, l) => acc + l.currentProductionPcs, 0);
  const avgEfficiency = totalLines > 0 
    ? lines.reduce((acc, l) => acc + l.efficiency, 0) / totalLines 
    : 0;

  // Header Design
  doc.setFillColor(15, 23, 42); // slate-900
  doc.rect(0, 0, 210, 40, "F");

  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(22);
  doc.text("PRODEXA INC.", 15, 18);
  
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(148, 163, 184); // slate-400
  doc.text("INDUSTRIAL SEWING FLOOR YIELD SYSTEMS", 15, 24);

  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.setTextColor(16, 185, 129); // emerald-500
  doc.text(`REPORT: DAILY YIELD & OUTPUT SUMMARY`, 15, 33);

  // Date and Metadata on the right
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(10);
  doc.setFont("helvetica", "bold");
  doc.text(`DATE: ${date}`, 145, 18);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(148, 163, 184);
  doc.text(`SHIFT: DAY SHIFT (10 HR)`, 145, 24);
  doc.text(`STATUS: ACTIVE FLOORS`, 145, 30);

  // Summary Cards Section
  doc.setTextColor(15, 23, 42);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.text("FACTORY FLOOR PERFORMANCE SUMMARY", 15, 52);

  // Draw 4 cards side by side
  const cards = [
    { label: "TOTAL SEWING LINES", val: totalLines.toString() },
    { label: "TARGET QUANTITY (PCS)", val: totalTarget.toLocaleString() },
    { label: "CURRENT PRODUCTION", val: totalProduction.toLocaleString() },
    { label: "AVERAGE EFFICIENCY", val: `${avgEfficiency.toFixed(1)}%` }
  ];

  cards.forEach((card, i) => {
    const x = 15 + i * 46;
    doc.setFillColor(248, 250, 252); // slate-50
    doc.setDrawColor(226, 232, 240); // slate-200
    doc.roundedRect(x, 58, 42, 20, 2, 2, "FD");

    doc.setFont("helvetica", "normal");
    doc.setFontSize(7);
    doc.setTextColor(100, 116, 139); // slate-500
    doc.text(card.label, x + 3, 64);

    doc.setFont("helvetica", "bold");
    doc.setFontSize(12);
    doc.setTextColor(15, 23, 42);
    doc.text(card.val, x + 3, 72);
  });

  // Detailed Table
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.setTextColor(15, 23, 42);
  doc.text("LINE-WISE OUTPUT breakdown", 15, 90);

  // Table header
  let y = 96;
  doc.setFillColor(15, 23, 42);
  doc.rect(15, y, 180, 8, "F");

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(8);
  doc.setFont("helvetica", "bold");
  doc.text("LINE", 17, y + 5.5);
  doc.text("SUPERVISOR", 35, y + 5.5);
  doc.text("BUYER", 75, y + 5.5);
  doc.text("STYLE", 100, y + 5.5);
  doc.text("TARGET (PCS)", 130, y + 5.5);
  doc.text("OUTPUT (PCS)", 155, y + 5.5);
  doc.text("EFFICIENCY", 180, y + 5.5);

  lines.forEach((line) => {
    y += 8;
    doc.setFillColor(255, 255, 255);
    doc.rect(15, y, 180, 8, "F");
    
    // Draw thin light borders
    doc.setDrawColor(241, 245, 249);
    doc.line(15, y + 8, 195, y + 8);

    doc.setFont("helvetica", "bold");
    doc.setTextColor(37, 99, 235); // blue-600
    doc.text(line.lineNo, 17, y + 5.5);

    doc.setFont("helvetica", "normal");
    doc.setTextColor(15, 23, 42);
    doc.text(line.supervisor.substring(0, 18), 35, y + 5.5);
    doc.text(line.buyer.substring(0, 12), 75, y + 5.5);
    doc.text(line.style.substring(0, 12), 100, y + 5.5);

    doc.setFont("helvetica", "bold");
    doc.text(line.targetPcs.toLocaleString(), 130, y + 5.5);
    doc.text(line.currentProductionPcs.toLocaleString(), 155, y + 5.5);

    // Color efficiency
    if (line.efficiency >= 85) {
      doc.setTextColor(16, 185, 129); // emerald-500
    } else if (line.efficiency >= 60) {
      doc.setTextColor(37, 99, 235); // blue-600
    } else {
      doc.setTextColor(245, 158, 11); // amber-500
    }
    doc.text(`${line.efficiency.toFixed(1)}%`, 180, y + 5.5);
  });

  // Footer
  y += 20;
  doc.setDrawColor(226, 232, 240);
  doc.line(15, y, 195, y);
  
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(148, 163, 184);
  doc.text("Generated by Prodexa MES • Confidential Floor Report", 15, y + 6);
  doc.text(`Page 1 of 1`, 180, y + 6);

  doc.save(`Prodexa_Daily_Yield_Report_${date}.pdf`);
}

export function generateMachineLogPDF(lines: ProductionLine[], date: string) {
  const doc = new jsPDF({
    orientation: "portrait",
    unit: "mm",
    format: "a4",
  });

  // Header Design
  doc.setFillColor(15, 23, 42); // slate-900
  doc.rect(0, 0, 210, 40, "F");

  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(22);
  doc.text("PRODEXA INC.", 15, 18);
  
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(148, 163, 184); // slate-400
  doc.text("INDUSTRIAL SEWING FLOOR YIELD SYSTEMS", 15, 24);

  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.setTextColor(239, 68, 68); // red-500
  doc.text(`REPORT: WEEKLY MACHINE UTILIZATION & IDLE LOG`, 15, 33);

  // Date and Metadata on the right
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(10);
  doc.setFont("helvetica", "bold");
  doc.text(`DATE: ${date}`, 145, 18);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(148, 163, 184);
  doc.text(`SHIFT: DAY SHIFT (10 HR)`, 145, 24);
  doc.text(`DEPT: MAINTENANCE & OPS`, 145, 30);

  // Machine Status Breakdown
  doc.setTextColor(15, 23, 42);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.text("MACHINE & SEWING STATION STANDINGS", 15, 52);

  const runningCount = lines.filter(l => l.status === "Running").length;
  const idleCount = lines.filter(l => l.status === "Idle").length;
  const breakdownCount = lines.filter(l => l.status === "Breakdown").length;

  const cards = [
    { label: "TOTAL MACHINES INSTALLED", val: (lines.length * 24).toString() },
    { label: "RUNNING LINES", val: runningCount.toString() },
    { label: "IDLE LINES", val: idleCount.toString() },
    { label: "BREAKDOWNS", val: breakdownCount.toString() }
  ];

  cards.forEach((card, i) => {
    const x = 15 + i * 46;
    doc.setFillColor(248, 250, 252);
    doc.setDrawColor(226, 232, 240);
    doc.roundedRect(x, 58, 42, 20, 2, 2, "FD");

    doc.setFont("helvetica", "normal");
    doc.setFontSize(7);
    doc.setTextColor(100, 116, 139);
    doc.text(card.label, x + 3, 64);

    doc.setFont("helvetica", "bold");
    doc.setFontSize(12);
    // Color code breakdowns
    if (card.label === "BREAKDOWNS" && breakdownCount > 0) {
      doc.setTextColor(239, 68, 68);
    } else {
      doc.setTextColor(15, 23, 42);
    }
    doc.text(card.val, x + 3, 72);
  });

  // Table
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.setTextColor(15, 23, 42);
  doc.text("STATION LOG DETAILS", 15, 90);

  let y = 96;
  doc.setFillColor(15, 23, 42);
  doc.rect(15, y, 180, 8, "F");

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(8);
  doc.setFont("helvetica", "bold");
  doc.text("LINE", 17, y + 5.5);
  doc.text("SUPERVISOR", 35, y + 5.5);
  doc.text("STATUS", 75, y + 5.5);
  doc.text("STYLE & CONFIG", 100, y + 5.5);
  doc.text("CURRENT HR PCS", 140, y + 5.5);
  doc.text("LAST UPDATED", 170, y + 5.5);

  lines.forEach((line) => {
    y += 8;
    doc.setFillColor(255, 255, 255);
    doc.rect(15, y, 180, 8, "F");

    doc.setDrawColor(241, 245, 249);
    doc.line(15, y + 8, 195, y + 8);

    doc.setFont("helvetica", "bold");
    doc.setTextColor(37, 99, 235);
    doc.text(line.lineNo, 17, y + 5.5);

    doc.setFont("helvetica", "normal");
    doc.setTextColor(15, 23, 42);
    doc.text(line.supervisor, 35, y + 5.5);

    // Color code Status
    if (line.status === "Running") {
      doc.setTextColor(16, 185, 129);
      doc.setFont("helvetica", "bold");
    } else if (line.status === "Idle") {
      doc.setTextColor(245, 158, 11);
      doc.setFont("helvetica", "bold");
    } else {
      doc.setTextColor(239, 68, 68);
      doc.setFont("helvetica", "bold");
    }
    doc.text(line.status, 75, y + 5.5);

    doc.setFont("helvetica", "normal");
    doc.setTextColor(15, 23, 42);
    doc.text(line.style, 100, y + 5.5);
    doc.text(`${line.currentHourPcs} Pcs`, 140, y + 5.5);
    doc.text(line.lastUpdated, 170, y + 5.5);
  });

  // Footer
  y += 20;
  doc.setDrawColor(226, 232, 240);
  doc.line(15, y, 195, y);
  
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(148, 163, 184);
  doc.text("Generated by Prodexa MES • Floor Maintenance Log", 15, y + 6);
  doc.text(`Page 1 of 1`, 180, y + 6);

  doc.save(`Prodexa_Machine_Log_${date}.pdf`);
}

export function generateSlaCompliancePDF(lines: ProductionLine[], date: string) {
  const doc = new jsPDF({
    orientation: "portrait",
    unit: "mm",
    format: "a4",
  });

  // Header Design
  doc.setFillColor(15, 23, 42); // slate-900
  doc.rect(0, 0, 210, 40, "F");

  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(22);
  doc.text("PRODEXA INC.", 15, 18);
  
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(148, 163, 184); // slate-400
  doc.text("INDUSTRIAL SEWING FLOOR YIELD SYSTEMS", 15, 24);

  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.setTextColor(59, 130, 246); // blue-500
  doc.text(`REPORT: BRAND SERVICE LEVEL AGREEMENT (SLA) AUDIT`, 15, 33);

  // Date and Metadata on the right
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(10);
  doc.setFont("helvetica", "bold");
  doc.text(`DATE: ${date}`, 145, 18);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(148, 163, 184);
  doc.text(`SHIFT: DAY SHIFT (10 HR)`, 145, 24);
  doc.text(`AUDIT: CLIENT COMPLIANCE`, 145, 30);

  // SLA Stats
  doc.setTextColor(15, 23, 42);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.text("BRAND DISPATCH & EXPORT READINESS", 15, 52);

  // Calculate compliance per brand
  const brandStats: { [key: string]: { total: number; compliant: number; output: number; target: number } } = {};
  
  lines.forEach(line => {
    const brand = line.buyer || "Unknown";
    if (!brandStats[brand]) {
      brandStats[brand] = { total: 0, compliant: 0, output: 0, target: 0 };
    }
    brandStats[brand].total += 1;
    brandStats[brand].output += line.currentProductionPcs;
    brandStats[brand].target += line.targetPcs;
    if (line.efficiency >= 70) {
      brandStats[brand].compliant += 1;
    }
  });

  const brandsArray = Object.keys(brandStats);
  const totalB = brandsArray.length;

  const totalLines = lines.length;
  const compliantLines = lines.filter(l => l.efficiency >= 70).length;
  const globalComplianceRate = totalLines > 0 ? (compliantLines / totalLines) * 100 : 0;

  const cards = [
    { label: "TOTAL CLIENT BRANDS", val: totalB.toString() },
    { label: "SLA THRESHOLD LIMIT", val: ">= 70.0% EFF" },
    { label: "SLA COMPLIANT LINES", val: `${compliantLines} / ${totalLines}` },
    { label: "COMPLIANCE LEVEL", val: `${globalComplianceRate.toFixed(1)}%` }
  ];

  cards.forEach((card, i) => {
    const x = 15 + i * 46;
    doc.setFillColor(248, 250, 252);
    doc.setDrawColor(226, 232, 240);
    doc.roundedRect(x, 58, 42, 20, 2, 2, "FD");

    doc.setFont("helvetica", "normal");
    doc.setFontSize(7);
    doc.setTextColor(100, 116, 139);
    doc.text(card.label, x + 3, 64);

    doc.setFont("helvetica", "bold");
    doc.setFontSize(12);
    if (card.label === "COMPLIANCE LEVEL") {
      doc.setTextColor(globalComplianceRate >= 75 ? 16 : 239, globalComplianceRate >= 75 ? 185 : 68, globalComplianceRate >= 75 ? 129 : 68);
    } else {
      doc.setTextColor(15, 23, 42);
    }
    doc.text(card.val, x + 3, 72);
  });

  // Table
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.setTextColor(15, 23, 42);
  doc.text("BRAND COMPLIANCE BREAKDOWN", 15, 90);

  let y = 96;
  doc.setFillColor(15, 23, 42);
  doc.rect(15, y, 180, 8, "F");

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(8);
  doc.setFont("helvetica", "bold");
  doc.text("BRAND NAME", 17, y + 5.5);
  doc.text("ACTIVE LINES", 55, y + 5.5);
  doc.text("TOTAL OUTPUT (PCS)", 85, y + 5.5);
  doc.text("TARGET (PCS)", 125, y + 5.5);
  doc.text("SLA STATUS", 165, y + 5.5);

  brandsArray.forEach((brand) => {
    y += 8;
    const stats = brandStats[brand];
    const rate = stats.total > 0 ? (stats.compliant / stats.total) * 100 : 0;
    
    doc.setFillColor(255, 255, 255);
    doc.rect(15, y, 180, 8, "F");

    doc.setDrawColor(241, 245, 249);
    doc.line(15, y + 8, 195, y + 8);

    doc.setFont("helvetica", "bold");
    doc.setTextColor(15, 23, 42);
    doc.text(brand, 17, y + 5.5);

    doc.setFont("helvetica", "normal");
    doc.text(`${stats.total} Lines`, 55, y + 5.5);
    doc.text(stats.output.toLocaleString(), 85, y + 5.5);
    doc.text(stats.target.toLocaleString(), 125, y + 5.5);

    // Color code Status
    if (rate >= 80) {
      doc.setTextColor(16, 185, 129); // emerald
      doc.setFont("helvetica", "bold");
      doc.text("FULLY COMPLIANT", 165, y + 5.5);
    } else if (rate >= 50) {
      doc.setTextColor(245, 158, 11); // amber
      doc.setFont("helvetica", "bold");
      doc.text("WARNING STATE", 165, y + 5.5);
    } else {
      doc.setTextColor(239, 68, 68); // red
      doc.setFont("helvetica", "bold");
      doc.text("CRITICAL OVERDUE", 165, y + 5.5);
    }
  });

  // Footer
  y += 20;
  doc.setDrawColor(226, 232, 240);
  doc.line(15, y, 195, y);
  
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(148, 163, 184);
  doc.text("Generated by Prodexa MES • SLA Audit Document", 15, y + 6);
  doc.text(`Page 1 of 1`, 180, y + 6);

  doc.save(`Prodexa_SLA_Compliance_Report_${date}.pdf`);
}
